name: Swift
env:
    XCODE_VERSION: "latest-stable"
on:
  push:
  pull_request:
jobs:
  swift-build:
    runs-on: macos-15 # macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - uses: actions/checkout@v3
      - run: swift build -v
      - run: swift test -v
